package org.fluentapis.jdbc.dsl;

import java.util.List;

import org.fluentapis.jdbc.converter.ListConverter;
import org.fluentapis.jdbc.converter.ResultSetConverter;
import org.fluentapis.jdbc.converter.ResultSetConverters;


public class ReturningParameterBuilder {

	private String[] columns;

	public ReturningParameterBuilder() {
		super();
	}
	
	public ReturningParameterBuilder(String[] columns) {
		this.columns = columns;
	}
	
	public ReturningParameter<Number> asNumber(){
		return new ReturningParameter<Number>(columns, ResultSetConverters.asNumber());
	}
	
	public ReturningParameter<List<Object[]>> asAutoGeneratedKeys(){
		return new ReturningParameter<List<Object[]>>(columns, new ListConverter());
	}

	public static ReturningParameterBuilder returning(String column) {
		return new ReturningParameterBuilder(new String[] { column });
	}
	
	public static class ReturningParameter<T> {

		private String[] columns;
		private ResultSetConverter<T> converter;

		public ReturningParameter(String[] columns, ResultSetConverter<T> converter) {
			this.columns = columns;
			this.converter = converter;
		}

		public String[] getColumns() {
			return columns;
		}

		public ResultSetConverter<T> getConverter() {
			return converter;
		}

	}

	
}
